// widget 변수를 선언하여 반환된 위젯 객체를 저장
var widget = new TradingView.widget({
  autosize: true,
  symbol: "BINANCE:BTCUSDT",
  interval: "D",
  timezone: "Etc/Utc",
  theme: "dark",
  style: "1",
  locale: "kr",
  toolbar_bg: "#f1f3f6",
  enable_publishing: true,
  withdateranges: false,
  hide_side_toolbar: true,
  allow_symbol_change: true,
  watchlist: [
    "FOREXCOM:SPX500",
    "FOREXCOM:NAS100",
    "BINANCE:BTCUSDT",
    "CRYPTOCAP:BTC.D",
    "BINANCE:ETHUSDT",
    "BINANCE:ETHBTC",
  ],
  details: true,
  hotlist: true,
  calendar: true,
  studies: ["STD;SMA"],
  container_id: "chart",
  show_popup_button: true,
  popup_width: "1000",
  popup_height: "650",
  studies_overrides: {
    "relative strength index.rsi.color": "#2196f3",
    "relative strength index.upper band.color": "#2100f5",
    "relative strength index.lower band.color": "#2100f5",
    "relative strength index.upper band.value": 80,
    "relative strength index.lower band.value": 20,
  },
  studies: ["RSI@tv-basicstudies"],
});
