new TradingView.widget({
  autosize: true,
  symbol: "BINANCE:BTCUSDT",
  interval: "D",
  timezzone: "Etc/Utc",
  theme: "dark",
  style: "1",
  locale: "kr",
  toolbar_bg: "#f1f3f6",
  enable_publishing: true,
  withdateranges: false,
  hide_side_toolbar: true,
  allow_symbol_change: true,
  watchlist: [
    "FOREXCOM:SPX500",
    "FOREXCOM:NAS100",
    // "NASDAQ:AAPL",
    // "NASDAQ:NVDA",
    // "NASDAQ:TSLA",
    "BINANCE:BTCUSDT",
    "CRYPTOCAP:BTC.D",
    "BINANCE:ETHUSDT",
    "BINANCE:ETHBTC",
  ],
  details: true,
  hotlist: true,
  calendar: true,
  studies: ["STD;SMA"],
  container_id: "chart",
  show_popup_button: true,
  popup_width: "1000",
  popup_height: "650",
});
